<?php
add_action('init', function () {
    register_post_type('unlimited-quiz', array(
        'labels' => array(
            'name' => 'Unlimited Quizzes',
            'singular_name' => 'Unlimited Quiz',
            'menu_name' => 'Unlimited Quizzes',
            'all_items' => 'All Unlimited Quizzes',
            'edit_item' => 'Edit Unlimited Quiz',
            'view_item' => 'View Unlimited Quiz',
            'view_items' => 'View Unlimited Quizzes',
            'add_new_item' => 'Add New Unlimited Quiz',
            'add_new' => 'Add New Unlimited Quiz',
            'new_item' => 'New Unlimited Quiz',
            'parent_item_colon' => 'Parent Unlimited Quiz:',
            'search_items' => 'Search Unlimited Quizzes',
            'not_found' => 'No unlimited quizzes found',
            'not_found_in_trash' => 'No unlimited quizzes found in Trash',
            'archives' => 'Unlimited Quiz Archives',
            'attributes' => 'Unlimited Quiz Attributes',
            'insert_into_item' => 'Insert into unlimited quiz',
            'uploaded_to_this_item' => 'Uploaded to this unlimited quiz',
            'filter_items_list' => 'Filter unlimited quizzes list',
            'filter_by_date' => 'Filter unlimited quizzes by date',
            'items_list_navigation' => 'Unlimited Quizzes list navigation',
            'items_list' => 'Unlimited Quizzes list',
            'item_published' => 'Unlimited Quiz published.',
            'item_published_privately' => 'Unlimited Quiz published privately.',
            'item_reverted_to_draft' => 'Unlimited Quiz reverted to draft.',
            'item_scheduled' => 'Unlimited Quiz scheduled.',
            'item_updated' => 'Unlimited Quiz updated.',
            'item_link' => 'Unlimited Quiz Link',
            'item_link_description' => 'A link to a unlimited quiz.',
        ),
        'public' => true,
        'show_in_rest' => true,
        'menu_position' => 5,
        'menu_icon' => 'dashicons-bank',
        'supports' => array(
            0 => 'title',
            1 => 'editor',
            2 => 'thumbnail',
            3 => 'custom-fields',
        ),
        'taxonomies' => array(
            0 => 'category',
        ),
        'delete_with_user' => false,
    ));
});
